export const MENTIONS_REQUEST = "MENTIONS_REQUEST";
export const MENTIONS_FILTER_REQUEST = "MENTIONS_FILTER_REQUEST";
export const MENTIONS_SUCCESS = "MENTIONS_SUCCESS";
export const MENTIONS_ERROR = "MENTIONS_ERROR";
export const MENTIONS_FILTER = "MENTIONS_FILTER";
export const MENTIONS_FILTER_SUCCESS = "MENTIONS_FILTER_SUCCESS";
export const MENTIONS_CHANGE_FILTER = "MENTIONS_CHANGE_FILTER";
